  
language: php

php:
    - 7.4

services:
    - mysql

before_install:
    - mysql -u root --password="" < db_backups/Dump20200524.sql

before_script:
    - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
    - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
    - sudo apt-get update -q
    - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
    - sudo systemctl restart mysql
    - sudo mysql_upgrade
    - mysql --version
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
