  
language: php

php:
    - 7.4

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS `coms3-misis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
    - mysql -u root --password="" < db_backups/coms3-misis_courses.sql
    - mysql -u root --password="" < db_backups/coms3-misis_enrollments.sql
    - mysql -u root --password="" < db_backups/coms3-misis_users.sql

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
